version: '3'
services:
  transpiler:
    build: ./takuan-webpack
    volumes:
      - ../src:/app/src
      - ../tests:/app/tests
      - ../dist/assets:/app/dist
      - ./config/webpack.config.js:/app/webpack.config.js
      - ./config/.babelrc:/app/.babelrc
      - ./config/.eslintrc:/app/.eslintrc
      - ./config/.eslintignore:/app/.eslintignore
      - ./config/.stylelintrc:/app/.stylelintrc
      - ./config/tsconfig.json:/app/tsconfig.json
      - ./config/tslint.json:/app/tslint.json
      - ../separate/pre-pre-dist:/app/separate/pre-pre-dist
      - ../separate/pre-dist:/app/separate/pre-dist
      - ../separate/dist:/app/separate/dist
      - ./config/postcss.config.js:/app/postcss.config.js
      - ./config/babel.config.js:/app/babel.config.js
      - ./config/webpack.config.separate.js:/app/webpack.config.separate.js
    ports:
      - 3000:3000
      - 3002:3002
    env_file: .env
    environment:
      - NODE_ENV=develop
      - SHELL=/bin/bash
    command: [yarn, webpack-dev-server, --hot, --colors, --port, '3000', --host, '0.0.0.0', ]



