version: '3'
services:


  scss:
    build: ./webpack
    volumes:
      - ../src:/app/src
      - ../pre-dist:/app/dist
      - ./config/webpack/.stylelintrc:/app/.stylelintrc
    command: [yarn, run, node-sass, -r, /app/src/assets/css, -o, /app/dist/assets/css, --watch]

  postcss:
    build: ./webpack
    volumes:
      - ../pre-dist:/app/src
      - ../dist/public:/app/dist
      - ./config/webpack/postcss.config.js:/app/postcss.config.js
    command: [yarn, run, postcss, /app/src/assets/css/*.css, --no-map, --dir, /app/dist/assets/css/, --watch]

  # htmlテンプレートエンジン
  pug:
    build: ./webpack
    volumes:
      - ../src/templates:/app/src
      - ../dist/public:/app/dist
    environment:
      - SHELL=/bin/bash
    command: [npm, run, watch]

  # コンパイルせずにファイルのコピーのみ行う
  files:
    build: ./webpack
    volumes:
      - ../src:/app/src
      - ../dist/public:/app/dist
    command: [yarn, run, cpx, "/app/src/**/*.{png,jpg}", /app/dist,  --watch]

  webpack:
    build: ./webpack
    volumes:
      - ../dist:/app/src
      - ../app/public:/app/dist
      # 設定ファイル
      - ./config/webpack/webpack.config.js:/app/webpack.config.js
    environment:
      - NODE_ENV=develop
    ports:
      - 8080:8080
    command: [yarn, run, webpack-dev-server, --hot]



